[package]
name = "pixi-pfx"
version = "0.3.1"
edition = "2024"
authors = ["pixi-pfx contributors <hi@prefix.dev>"]
license = "BSD-3-Clause"
repository = "https://github.com/prefix-dev/pixi-pfx"

[dependencies]
clap = { version = "4.5", features = ["derive", "env"] }
cynic = "3"
reqwest = { version = "0.13", default-features = false, features = ["json", "rustls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
thiserror = "2"
tabwriter = "1.4.1"
rattler_networking = { version = "0.30.5", default-features = false, features = ["rustls", "system-integration"] }

[dev-dependencies]
cynic-introspection = "3"

[features]
online-tests = []
